### ISSUE TITLE
How did the 1000_ids.json file come about？

### ISSUE THREAD

**Issue by XiaozhuLove** [HongruCai/PersonalWAB#1]
![微信截图_20241025213541](https://github.com/user-attachments/assets/6f951513-056a-42ea-8eff-b0195647a3ba)

Thank you very much for your work. As shown in the picture, how did this "1000_ids.json" file come about? Could you please provide it? 
I look forward to your reply.

**Comment by HongruCai** [comment]
Thank you for reaching out and for your interest in our work!

I have now uploaded the 1000_ids.json file to the repository as requested. Please let me know if there is anything else I can help with.

Best regards!

**Comment by XiaozhuLove** [comment]
After I re-pulled the code, I ran the script scripts/run_singleturn.sh and it indicated that the function_selection_file and memory_file were missing. Could you please tell me how these files are obtained? Do I need to run a specific code to generate them, or could you provide them? Thank you very much！
![微信截图_20241030211928](https://github.com/user-attachments/assets/9f47d557-aca5-4166-9919-3afe5fab9b5c)

**Comment by HongruCai** [comment]
Hi, XiaozhuLove.

The function_selection_file is generated through our PUMA framework, providing the specific functions for each user instruction. To create this file for testing, you will need to follow the training steps outlined in the PUMA framework (at least fine-tune on function data).

The memory_file serves as a memory record for the InteRecAgent and is only needed if you choose the InteRecAgent memory mechanism. For guidance on constructing this file, you may refer to our paper to see details and construct on your own. A simple example script is also available in scripts/tools to help you generate the memory file.

**Comment by XiaozhuLove** [comment]
> Hi, XiaozhuLove.
> 
> The function_selection_file is generated through our PUMA framework, providing the specific functions for each user instruction. To create this file for testing, you will need to follow the training steps outlined in the PUMA framework (at least fine-tune on function data).
> 
> The memory_file serves as a memory record for the InteRecAgent and is only needed if you choose the InteRecAgent memory mechanism. For guidance on constructing this file, you may refer to our paper to see details and construct on your own. A simple example script is also available in scripts/tools to help you generate the memory file.

 Thank you for your reply, I'd like to ask further if it's possible to run through the entire code pipeline, from generating results to evaluation, without training（without the aforementioned files）. Thank you very much！

**Comment by HongruCai** [comment]
Yes, it is possible. You can try other methods, such as Relevant or ReAct, which do not require additional files.
